FROM registry.access.redhat.com/ubi9/go-toolset@sha256:8a634d63713a073d7a1e086a322e57b148eef9620834fc8266df63d9294dff1b as builder
USER 0
WORKDIR /work
COPY ./ .

ENV GOTOOLCHAIN=auto \
    GOSUMDB=sum.golang.org

RUN go build -o domainproxyserver cmd/server/main.go && \
    go build -o domainproxyclient cmd/client/main.go

FROM quay.io/konflux-ci/buildah-task:latest@sha256:4d8273444b0f2781264c232e12e88449bbf078c99e3da2a7f6dcaaf27bc53712
USER 0
WORKDIR /work/

COPY --from=builder /work/domainproxyserver /app/domain-proxy-server
COPY --from=builder /work/domainproxyclient /app/domain-proxy-client
