FROM registry.access.redhat.com/ubi9/go-toolset@sha256:d4692022b557e93afdf89d4b28ae07cbb7e2a0cdbf13d031c5891e9494ac4eef as builder
USER 0
WORKDIR /work
COPY ./ .

ENV GOTOOLCHAIN=auto \
    GOSUMDB=sum.golang.org

RUN go build -o domainproxyserver cmd/server/main.go && \
    go build -o domainproxyclient cmd/client/main.go

FROM quay.io/konflux-ci/buildah-task:latest@sha256:ab0ba3b70f99faa74d2dd737422a965197af4922dec0109113bc535a94db0dfd
USER 0
WORKDIR /work/

COPY --from=builder /work/domainproxyserver /app/domain-proxy-server
COPY --from=builder /work/domainproxyclient /app/domain-proxy-client
